using Microsoft.AspNetCore.Authorization; using Microsoft.AspNetCore.Mvc; using Microsoft.EntityFrameworkCore; using StockManagement.Data; using StockManagement.Models; using StockManagement.Services;
namespace StockManagement.Controllers;
[Authorize(Roles=Roles.Admin+","+Roles.Manager+","+Roles.Staff)] public class ProductsController:Controller {readonly ApplicationDbContext _db;readonly AuditService _audit;public ProductsController(ApplicationDbContext db,AuditService audit){_db=db;_audit=audit;}
public IActionResult Index(string? search){var q=_db.Products.Include(x=>x.Category).AsQueryable();if(!string.IsNullOrWhiteSpace(search))q=q.Where(x=>x.Name.Contains(search)||x.SKU.Contains(search));ViewBag.Search=search;return View(q.OrderBy(x=>x.Name).ToList());}
public IActionResult Create(){ViewBag.Categories=_db.Categories.OrderBy(x=>x.Name).ToList();return View(new Product{SKU="SKU-"+DateTime.Now.ToString("HHmmss")});}
[HttpPost,ValidateAntiForgeryToken]public IActionResult Create(Product p){if(_db.Products.Any(x=>x.SKU==p.SKU))ModelState.AddModelError("SKU","SKU already exists.");if(!ModelState.IsValid)return View(p);_db.Products.Add(p);_db.SaveChanges();_audit.Add("Product","Create",$"Created {p.SKU} - {p.Name}",User.Identity?.Name??"System");TempData["Success"]="Product created successfully.";return RedirectToAction(nameof(Index));}
public IActionResult Edit(int id){var p=_db.Products.Find(id);if(p==null)return NotFound();ViewBag.Categories=_db.Categories.OrderBy(x=>x.Name).ToList();return View(p);}
[HttpPost,ValidateAntiForgeryToken]public IActionResult Edit(Product p){if(!ModelState.IsValid)return View(p);var e=_db.Products.Find(p.Id);if(e==null)return NotFound();e.SKU=p.SKU;e.Name=p.Name;e.CategoryId=p.CategoryId;e.Unit=p.Unit;e.UnitPrice=p.UnitPrice;e.ReorderLevel=p.ReorderLevel;e.Status=p.Status;_db.SaveChanges();_audit.Add("Product","Update",$"Updated {p.SKU} - {p.Name}",User.Identity?.Name??"System");TempData["Success"]="Product updated successfully.";return RedirectToAction(nameof(Index));}
[HttpPost,ValidateAntiForgeryToken]public IActionResult Delete(int id){var p=_db.Products.Find(id);if(p!=null){_db.Products.Remove(p);try{_db.SaveChanges();TempData["Success"]="Product deleted.";}catch{TempData["Error"]="Product cannot be deleted because it is referenced by transactions.";}}return RedirectToAction(nameof(Index));}
}
