using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StockManagement.Models;
public static class Roles { public const string Admin="Admin"; public const string Manager="Manager"; public const string Staff="Staff"; }
public class AppUser { public int Id{get;set;} [Required,MaxLength(100)] public string FullName{get;set;}=""; [Required,EmailAddress,MaxLength(150)] public string Email{get;set;}=""; [Required] public string PasswordHash{get;set;}=""; public string Role{get;set;}=Roles.Staff; public bool IsActive{get;set;}=true; }
public class Category { public int Id{get;set;} [Required,MaxLength(80)] public string Name{get;set;}=""; [MaxLength(200)] public string Description{get;set;}=""; public ICollection<Product> Products{get;set;}=new List<Product>(); }
public class Product { public int Id{get;set;} [Required,MaxLength(30)] public string SKU{get;set;}=""; [Required,MaxLength(120)] public string Name{get;set;}=""; public int CategoryId{get;set;} public Category? Category{get;set;} [MaxLength(30)] public string Unit{get;set;}="Piece"; [Range(0,999999999)] public decimal UnitPrice{get;set;} [Range(0,int.MaxValue)] public int ReorderLevel{get;set;} [Range(0,int.MaxValue)] public int CurrentStock{get;set;} [MaxLength(30)] public string Status{get;set;}="Active"; public DateTime CreatedAt{get;set;}=DateTime.UtcNow; }
public class Supplier { public int Id{get;set;} [Required,MaxLength(120)] public string Name{get;set;}=""; [MaxLength(150)] public string Email{get;set;}=""; [MaxLength(30)] public string Phone{get;set;}=""; [MaxLength(250)] public string Address{get;set;}=""; public bool IsActive{get;set;}=true; }
public class Customer { public int Id{get;set;} [Required,MaxLength(120)] public string Name{get;set;}=""; [MaxLength(150)] public string Email{get;set;}=""; [MaxLength(30)] public string Phone{get;set;}=""; }
public class Purchase { public int Id{get;set;} public int SupplierId{get;set;} public Supplier? Supplier{get;set;} public DateTime PurchaseDate{get;set;}=DateTime.UtcNow; public decimal TotalAmount{get;set;} public string Status{get;set;}="Completed"; public string InvoiceNo{get;set;}=""; public ICollection<PurchaseDetail> Details{get;set;}=new List<PurchaseDetail>(); }
public class PurchaseDetail { public int Id{get;set;} public int PurchaseId{get;set;} public Purchase? Purchase{get;set;} public int ProductId{get;set;} public Product? Product{get;set;} public int Quantity{get;set;} public decimal UnitCost{get;set;} [NotMapped] public decimal LineTotal=>Quantity*UnitCost; }
public class Sale { public int Id{get;set;} public int? CustomerId{get;set;} public Customer? Customer{get;set;} public DateTime SaleDate{get;set;}=DateTime.UtcNow; public decimal TotalAmount{get;set;} public string Status{get;set;}="Completed"; public string InvoiceNo{get;set;}=""; public ICollection<SaleDetail> Details{get;set;}=new List<SaleDetail>(); }
public class SaleDetail { public int Id{get;set;} public int SaleId{get;set;} public Sale? Sale{get;set;} public int ProductId{get;set;} public Product? Product{get;set;} public int Quantity{get;set;} public decimal UnitPrice{get;set;} [NotMapped] public decimal LineTotal=>Quantity*UnitPrice; }
public class StockTransaction { public int Id{get;set;} public int ProductId{get;set;} public Product? Product{get;set;} public string TransactionType{get;set;}="IN"; public int Quantity{get;set;} public decimal UnitCost{get;set;} public DateTime TransactionDate{get;set;}=DateTime.UtcNow; public string ReferenceNo{get;set;}=""; }
public class AuditLog { public int Id{get;set;} public string EntityName{get;set;}=""; public string ActionType{get;set;}=""; public string Description{get;set;}=""; public string ChangedBy{get;set;}="System"; public DateTime ChangedAt{get;set;}=DateTime.UtcNow; }
public class DashboardVm { public int Products{get;set;} public int Categories{get;set;} public int Suppliers{get;set;} public int Customers{get;set;} public int LowStock{get;set;} public decimal SalesToday{get;set;} public decimal PurchasesToday{get;set;} public List<Product> LowStockProducts{get;set;}=new(); public List<Sale> RecentSales{get;set;}=new(); }
public class SaleCreateVm { public int? CustomerId{get;set;} public List<SaleLineVm> Lines{get;set;}=new(){new()}; }
public class SaleLineVm { public int ProductId{get;set;} public int Quantity{get;set;} public decimal UnitPrice{get;set;} }
public class PurchaseCreateVm { public int SupplierId{get;set;} public List<PurchaseLineVm> Lines{get;set;}=new(){new()}; }
public class PurchaseLineVm { public int ProductId{get;set;} public int Quantity{get;set;} public decimal UnitCost{get;set;} }
